// Package bank provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package bank

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"github.com/shopspring/decimal"
)

// Defines values for PaymentStatus.
const (
	Captured      PaymentStatus = "captured"
	Preauthorized PaymentStatus = "preauthorized"
)

// Account defines model for Account.
type Account struct {
	AccountNumber string         `json:"account_number"`
	Balance       Decimal        `json:"balance"`
	Card          *Card          `json:"card,omitempty"`
	History       []BankTransfer `json:"history"`
}

// BankTransfer defines model for BankTransfer.
type BankTransfer struct {
	Amount                Decimal   `json:"amount"`
	CreatedAt             time.Time `json:"created_at"`
	Currency              string    `json:"currency"`
	ExternalAccountNumber string    `json:"external_account_number"`
	ReceiverDetails       string    `json:"receiver_details"`
	Reference             string    `json:"reference"`
}

// BankTransferRequest defines model for BankTransferRequest.
type BankTransferRequest struct {
	Amount              Decimal `json:"amount"`
	Currency            string  `json:"currency"`
	IdempotencyKey      string  `json:"idempotency_key"`
	ReceiverDetails     string  `json:"receiver_details"`
	Reference           string  `json:"reference"`
	SourceAccountNumber string  `json:"source_account_number"`
	TargetAccountNumber string  `json:"target_account_number"`
}

// Card defines model for Card.
type Card struct {
	CardNumber string `json:"card_number"`
}

// Decimal defines model for Decimal.
type Decimal = decimal.Decimal

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message
	Message string `json:"message"`
}

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// PreauthorizeRequest defines model for PreauthorizeRequest.
type PreauthorizeRequest struct {
	Amount         Decimal            `json:"amount"`
	CardNumber     string             `json:"card_number"`
	Currency       string             `json:"currency"`
	Cvv            string             `json:"cvv"`
	ExpiryDate     openapi_types.Date `json:"expiry_date"`
	IdempotencyKey string             `json:"idempotency_key"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CreateAccountJSONBody defines parameters for CreateAccount.
type CreateAccountJSONBody struct {
	InitialBalance Decimal `json:"initial_balance"`

	// MerchantId Merchant ID to link this account to
	MerchantId string `json:"merchant_id"`
}

// CapturePaymentJSONBody defines parameters for CapturePayment.
type CapturePaymentJSONBody struct {
	Amount Decimal `json:"amount"`

	// MerchantId Merchant/platform entity ID to route payment to
	MerchantId string `json:"merchant_id"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody CreateAccountJSONBody

// ScheduleBankTransferJSONRequestBody defines body for ScheduleBankTransfer for application/json ContentType.
type ScheduleBankTransferJSONRequestBody = BankTransferRequest

// PreauthorizePaymentJSONRequestBody defines body for PreauthorizePayment for application/json ContentType.
type PreauthorizePaymentJSONRequestBody = PreauthorizeRequest

// CapturePaymentJSONRequestBody defines body for CapturePayment for application/json ContentType.
type CapturePaymentJSONRequestBody CapturePaymentJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateAccountWithBody request with any body
	CreateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAccount(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccount request
	GetAccount(ctx context.Context, bankAccountNumber string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ScheduleBankTransferWithBody request with any body
	ScheduleBankTransferWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ScheduleBankTransfer(ctx context.Context, body ScheduleBankTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PreauthorizePaymentWithBody request with any body
	PreauthorizePaymentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PreauthorizePayment(ctx context.Context, body PreauthorizePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPayment request
	GetPayment(ctx context.Context, paymentNonce string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CapturePaymentWithBody request with any body
	CapturePaymentWithBody(ctx context.Context, paymentNonce string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CapturePayment(ctx context.Context, paymentNonce string, body CapturePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAccountRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAccount(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAccountRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccount(ctx context.Context, bankAccountNumber string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountRequest(c.Server, bankAccountNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ScheduleBankTransferWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewScheduleBankTransferRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ScheduleBankTransfer(ctx context.Context, body ScheduleBankTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewScheduleBankTransferRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PreauthorizePaymentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPreauthorizePaymentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PreauthorizePayment(ctx context.Context, body PreauthorizePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPreauthorizePaymentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPayment(ctx context.Context, paymentNonce string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPaymentRequest(c.Server, paymentNonce)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CapturePaymentWithBody(ctx context.Context, paymentNonce string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCapturePaymentRequestWithBody(c.Server, paymentNonce, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CapturePayment(ctx context.Context, paymentNonce string, body CapturePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCapturePaymentRequest(c.Server, paymentNonce, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateAccountRequest calls the generic CreateAccount builder with application/json body
func NewCreateAccountRequest(server string, body CreateAccountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAccountRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAccountRequestWithBody generates requests for CreateAccount with any type of body
func NewCreateAccountRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAccountRequest generates requests for GetAccount
func NewGetAccountRequest(server string, bankAccountNumber string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bank_account_number", runtime.ParamLocationPath, bankAccountNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewScheduleBankTransferRequest calls the generic ScheduleBankTransfer builder with application/json body
func NewScheduleBankTransferRequest(server string, body ScheduleBankTransferJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewScheduleBankTransferRequestWithBody(server, "application/json", bodyReader)
}

// NewScheduleBankTransferRequestWithBody generates requests for ScheduleBankTransfer with any type of body
func NewScheduleBankTransferRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bank-transfers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPreauthorizePaymentRequest calls the generic PreauthorizePayment builder with application/json body
func NewPreauthorizePaymentRequest(server string, body PreauthorizePaymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPreauthorizePaymentRequestWithBody(server, "application/json", bodyReader)
}

// NewPreauthorizePaymentRequestWithBody generates requests for PreauthorizePayment with any type of body
func NewPreauthorizePaymentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/payments/preauth")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPaymentRequest generates requests for GetPayment
func NewGetPaymentRequest(server string, paymentNonce string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "payment_nonce", runtime.ParamLocationPath, paymentNonce)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/payments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCapturePaymentRequest calls the generic CapturePayment builder with application/json body
func NewCapturePaymentRequest(server string, paymentNonce string, body CapturePaymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCapturePaymentRequestWithBody(server, paymentNonce, "application/json", bodyReader)
}

// NewCapturePaymentRequestWithBody generates requests for CapturePayment with any type of body
func NewCapturePaymentRequestWithBody(server string, paymentNonce string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "payment_nonce", runtime.ParamLocationPath, paymentNonce)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/payments/%s/capture", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateAccountWithBodyWithResponse request with any body
	CreateAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error)

	CreateAccountWithResponse(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error)

	// GetAccountWithResponse request
	GetAccountWithResponse(ctx context.Context, bankAccountNumber string, reqEditors ...RequestEditorFn) (*GetAccountResponse, error)

	// ScheduleBankTransferWithBodyWithResponse request with any body
	ScheduleBankTransferWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ScheduleBankTransferResponse, error)

	ScheduleBankTransferWithResponse(ctx context.Context, body ScheduleBankTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*ScheduleBankTransferResponse, error)

	// PreauthorizePaymentWithBodyWithResponse request with any body
	PreauthorizePaymentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PreauthorizePaymentResponse, error)

	PreauthorizePaymentWithResponse(ctx context.Context, body PreauthorizePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*PreauthorizePaymentResponse, error)

	// GetPaymentWithResponse request
	GetPaymentWithResponse(ctx context.Context, paymentNonce string, reqEditors ...RequestEditorFn) (*GetPaymentResponse, error)

	// CapturePaymentWithBodyWithResponse request with any body
	CapturePaymentWithBodyWithResponse(ctx context.Context, paymentNonce string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CapturePaymentResponse, error)

	CapturePaymentWithResponse(ctx context.Context, paymentNonce string, body CapturePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CapturePaymentResponse, error)
}

type CreateAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Account
	JSON400      *BadRequest
}

// Status returns HTTPResponse.Status
func (r CreateAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Account
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ScheduleBankTransferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
}

// Status returns HTTPResponse.Status
func (r ScheduleBankTransferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ScheduleBankTransferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PreauthorizePaymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// PaymentNonce Token to be used for capturing the payment
		PaymentNonce string `json:"payment_nonce"`
	}
	JSON400 *BadRequest
}

// Status returns HTTPResponse.Status
func (r PreauthorizePaymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PreauthorizePaymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPaymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status PaymentStatus `json:"status"`
	}
	JSON404 *NotFound
}

// Status returns HTTPResponse.Status
func (r GetPaymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPaymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CapturePaymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r CapturePaymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CapturePaymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateAccountWithBodyWithResponse request with arbitrary body returning *CreateAccountResponse
func (c *ClientWithResponses) CreateAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error) {
	rsp, err := c.CreateAccountWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAccountResponse(rsp)
}

func (c *ClientWithResponses) CreateAccountWithResponse(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error) {
	rsp, err := c.CreateAccount(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAccountResponse(rsp)
}

// GetAccountWithResponse request returning *GetAccountResponse
func (c *ClientWithResponses) GetAccountWithResponse(ctx context.Context, bankAccountNumber string, reqEditors ...RequestEditorFn) (*GetAccountResponse, error) {
	rsp, err := c.GetAccount(ctx, bankAccountNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountResponse(rsp)
}

// ScheduleBankTransferWithBodyWithResponse request with arbitrary body returning *ScheduleBankTransferResponse
func (c *ClientWithResponses) ScheduleBankTransferWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ScheduleBankTransferResponse, error) {
	rsp, err := c.ScheduleBankTransferWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseScheduleBankTransferResponse(rsp)
}

func (c *ClientWithResponses) ScheduleBankTransferWithResponse(ctx context.Context, body ScheduleBankTransferJSONRequestBody, reqEditors ...RequestEditorFn) (*ScheduleBankTransferResponse, error) {
	rsp, err := c.ScheduleBankTransfer(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseScheduleBankTransferResponse(rsp)
}

// PreauthorizePaymentWithBodyWithResponse request with arbitrary body returning *PreauthorizePaymentResponse
func (c *ClientWithResponses) PreauthorizePaymentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PreauthorizePaymentResponse, error) {
	rsp, err := c.PreauthorizePaymentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePreauthorizePaymentResponse(rsp)
}

func (c *ClientWithResponses) PreauthorizePaymentWithResponse(ctx context.Context, body PreauthorizePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*PreauthorizePaymentResponse, error) {
	rsp, err := c.PreauthorizePayment(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePreauthorizePaymentResponse(rsp)
}

// GetPaymentWithResponse request returning *GetPaymentResponse
func (c *ClientWithResponses) GetPaymentWithResponse(ctx context.Context, paymentNonce string, reqEditors ...RequestEditorFn) (*GetPaymentResponse, error) {
	rsp, err := c.GetPayment(ctx, paymentNonce, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPaymentResponse(rsp)
}

// CapturePaymentWithBodyWithResponse request with arbitrary body returning *CapturePaymentResponse
func (c *ClientWithResponses) CapturePaymentWithBodyWithResponse(ctx context.Context, paymentNonce string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CapturePaymentResponse, error) {
	rsp, err := c.CapturePaymentWithBody(ctx, paymentNonce, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCapturePaymentResponse(rsp)
}

func (c *ClientWithResponses) CapturePaymentWithResponse(ctx context.Context, paymentNonce string, body CapturePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CapturePaymentResponse, error) {
	rsp, err := c.CapturePayment(ctx, paymentNonce, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCapturePaymentResponse(rsp)
}

// ParseCreateAccountResponse parses an HTTP response from a CreateAccountWithResponse call
func ParseCreateAccountResponse(rsp *http.Response) (*CreateAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetAccountResponse parses an HTTP response from a GetAccountWithResponse call
func ParseGetAccountResponse(rsp *http.Response) (*GetAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseScheduleBankTransferResponse parses an HTTP response from a ScheduleBankTransferWithResponse call
func ParseScheduleBankTransferResponse(rsp *http.Response) (*ScheduleBankTransferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ScheduleBankTransferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePreauthorizePaymentResponse parses an HTTP response from a PreauthorizePaymentWithResponse call
func ParsePreauthorizePaymentResponse(rsp *http.Response) (*PreauthorizePaymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PreauthorizePaymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// PaymentNonce Token to be used for capturing the payment
			PaymentNonce string `json:"payment_nonce"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetPaymentResponse parses an HTTP response from a GetPaymentWithResponse call
func ParseGetPaymentResponse(rsp *http.Response) (*GetPaymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPaymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status PaymentStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCapturePaymentResponse parses an HTTP response from a CapturePaymentWithResponse call
func ParseCapturePaymentResponse(rsp *http.Response) (*CapturePaymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CapturePaymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
